[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.14.0"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_DEBUG = "module,http,net"
  DEBUG = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  command = "npm run dev"
  port = 3000
  framework = "astro"

# Usuwamy przekierowanie SPA i pozwalamy adapterowi Astro stworzyć własne przekierowania
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[build.processing]
  skip_processing = false 