[build]
  command = "npm run netlify:build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "22.14.0", NODE_OPTIONS = "--max_old_space_size=4096" }

# Te zmienne muszą być ustawione w ustawieniach projektu Netlify
[build.environment]
  PUBLIC_SUPABASE_URL = ""
  PUBLIC_SUPABASE_KEY = ""
  OPENROUTER_API_KEY = ""
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]
  external_node_modules = ["@supabase/supabase-js"]

[dev]
  command = "npm run dev"
  port = 3000
  framework = "astro"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 