[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "20" }

# Te zmienne muszą być ustawione w ustawieniach projektu Netlify
[build.environment]
  PUBLIC_SUPABASE_URL = ""
  PUBLIC_SUPABASE_KEY = ""
  OPENROUTER_API_KEY = ""

[functions]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  port = 3000
  framework = "astro"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false 