name: Test, Build & Deploy na Netlify

on:
  push:
    branches: [master]
  workflow_dispatch: # Uruchamianie ręczne

jobs:
  test-and-build:
    name: Test i Build
    runs-on: ubuntu-latest
    env:
      # Zmienne dla klienta (z prefiksem PUBLIC_)
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
      # Zmienne dla serwera (bez prefiksu PUBLIC_)
      SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
      # Pozostałe zmienne
      E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
      E2E_USERNAME: ${{ secrets.E2E_USERNAME }}
      E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Instalacja zależności
        run: npm ci

      - name: Sprawdzenie formatowania kodu
        run: npm run format -- --check || echo "Sprawdzenie formatowania nie powiodło się, ale kontynuujemy"

      - name: Sprawdzenie lintów
        run: npm run lint || echo "Sprawdzenie lintów nie powiodło się, ale kontynuujemy"

      - name: Sprawdzenie typów TypeScript
        run: npm run typecheck || echo "Sprawdzenie typów nie powiodło się, ale kontynuujemy"

      - name: Uruchomienie testów jednostkowych
        run: npm run test

      # - name: Przygotuj plik .env.test
      #   run: |
      #     cat > .env.test << EOF
      #     PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}
      #     PUBLIC_SUPABASE_KEY=${{ secrets.PUBLIC_SUPABASE_KEY }}
      #     SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }}
      #     SUPABASE_KEY=${{ secrets.PUBLIC_SUPABASE_KEY }}
      #     E2E_USERNAME_ID=${{ secrets.E2E_USERNAME_ID }}
      #     E2E_USERNAME=${{ secrets.E2E_USERNAME }}
      #     E2E_PASSWORD=${{ secrets.E2E_PASSWORD }}
      #     EOF
      #     cat .env.test

      # - name: Instalacja przeglądarek Playwright
      #   run: npx playwright install --with-deps chromium

      # - name: Uruchomienie testów e2e
      #   run: |
      #     # Wyświetl zawartość zmiennych środowiskowych (zamaskowane)
      #     echo "Sprawdzanie zmiennych środowiskowych:"
      #     echo "PUBLIC_SUPABASE_URL jest ustawiony: ${{ env.PUBLIC_SUPABASE_URL != '' }}"
      #     echo "PUBLIC_SUPABASE_KEY jest ustawiony: ${{ env.PUBLIC_SUPABASE_KEY != '' }}"
      #     echo "SUPABASE_URL jest ustawiony: ${{ env.SUPABASE_URL != '' }}"
      #     echo "SUPABASE_KEY jest ustawiony: ${{ env.SUPABASE_KEY != '' }}"

      #     # Uruchom testy e2e z bezpośrednim przekazaniem zmiennych
      #     npm run test:e2e || echo "Testy e2e nie powiodły się, ale kontynuujemy"

      - name: Build produkcyjny
        run: npm run build
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}

      - name: Archiwizacja artefaktów
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  deploy:
    name: Wdrożenie na Netlify
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Pobierz build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Wdrożenie na Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Wdrożenie z GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
