name: Pull Request Checks

on:
  pull_request:
    branches: [master]
  workflow_dispatch: # Możliwość ręcznego uruchomienia

jobs:
  lint:
    name: Lintowanie kodu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Instalacja zależności
        run: npm ci

      - name: Sprawdzenie lintów
        run: npm run lint

  unit-test:
    name: Testy jednostkowe
    needs: lint
    runs-on: ubuntu-latest
    env:
      PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
      PUBLIC_SUPABASE_KEY: ${{ secrets.PUBLIC_SUPABASE_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

    steps:
      - name: Checkout kodu
        uses: actions/checkout@v4

      - name: Konfiguracja Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Instalacja zależności
        run: npm ci

      - name: Uruchomienie testów jednostkowych z coverage
        run: npm run test:coverage

      - name: Zapisz wyniki testów jednostkowych
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 7

  status-comment:
    name: Komentarz do PR
    if: ${{ always() }}
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdź status poprzednich kroków
        if: |
          needs.lint.result == 'success' &&
          needs.unit-test.result == 'success'
        id: check
        run: echo "::set-output name=success::true"

      - name: Dodaj komentarz o sukcesie
        if: steps.check.outputs.success == 'true'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: build-success
          message: |
            ## ✅ Wszystkie testy przeszły pomyślnie!

            Zweryfikowano:
            - ✓ Lintowanie kodu
            - ✓ Testy jednostkowe

            Pull Request jest gotowy do przeglądu.

      - name: Dodaj komentarz o niepowodzeniu
        if: ${{ failure() || cancelled() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: build-failure
          message: |
            ## ❌ Wykryto problemy w trakcie weryfikacji!

            Status:
            - Lintowanie kodu: ${{ needs.lint.result == 'success' && '✓' || '❌' }}
            - Testy jednostkowe: ${{ needs.unit-test.result == 'success' && '✓' || '❌' }}

            Proszę sprawdzić logi dla poszczególnych zadań, aby rozwiązać problemy.
